name: ajna

description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.2.2

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.1
  geolocator: ^12.0.0
  google_maps_flutter: ^2.7.0
  http: ^1.2.1
  local_auth: ^2.2.0
  logger: ^2.3.0
  marquee: ^2.2.3
  package_info_plus: ^8.0.0
  path_provider: ^2.1.3
  pattern_lock: ^2.0.0
  permission_handler: ^11.3.1
  pin_code_fields: ^8.0.1
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  share_plus: ^9.0.0
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0
  mailer: ^5.0.0
  flutter_dotenv: ^5.0.2
  dio: ^4.0.0
  flutter_downloader: ^1.11.7

  device_info_plus: ^10.1.0
  dropdown_button2: ^2.0.0
  image_picker: ^0.8.7+4
  camera: ^0.11.0+1
  http_parser: ^4.0.2
  intl: any
  pdf: ^3.10.8
  printing: ^5.12.0
  cupertino_icons: ^1.0.6
  flutter_login: ^5.0.0
  dropdown_search: ^5.0.6
  archive: ^3.1.2
  xml: ^6.0.1
  fluttertoast: any
  font_awesome_flutter: ^10.7.0
  connectivity_plus: ^3.0.6
  sqflite: ^2.0.2+2
  timezone: ^0.9.4
  image: ^4.0.15
  workmanager: ^0.5.2
  firebase_messaging: ^14.8.0
  flutter_local_notifications: ^17.0.0
  firebase_core: ^2.30.0
  firebase_auth: ^4.19.2
  cloud_firestore: ^4.17.0
  multi_select_flutter: ^4.0.0
  fading_edge_scrollview: 3.0.0
  animated_text_kit: ^4.2.1
  flutter_tts: ^4.2.1
  confetti: ^0.7.0
  flutter_ringtone_player: ^3.2.0
  audioplayers: ^5.2.1
  tflite_flutter: ^0.9.0
  tflite_flutter_plus: ^0.0.1
  google_fonts: ^6.1.0
  # google_mlkit_face_detection: ^0.7.0
  android_intent_plus: ^4.0.1
  open_file: ^3.3.2
  
  file_picker: ^6.1.1
  external_path: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/logo.png
    - lib/assets/images/sbricon.png
    - lib/assets/images/loginbg.png
    - lib/assets/images/image-background.png
    - lib/assets/images/background-profile.jpg
    - lib/assets/images/avatar.png
    - lib/assets/images/qrgenerate.png
    - lib/assets/images/consumption.png
    - lib/assets/images/qrscan.png
    - lib/assets/images/reset_andriod_id.png
    - lib/assets/images/qr_assign.png
    - lib/assets/images/qr_regenarate.png
    - lib/assets/images/scan_report.png
    - lib/assets/images/user_registration.png
    - lib/assets/images/site_visit.png
    - lib/assets/images/sales.png
    - lib/assets/images/crm-icon.png
    - lib/assets/images/issue.png
    - lib/assets/images/lead.png
    - lib/assets/images/attendace.png
    - lib/assets/images/account.png
    - lib/assets/images/calendar.png
    - lib/assets/images/ajna.png
    - lib/assets/images/corenuts-logo.png
    - lib/assets/images/ot.png
    - lib/assets/images/otreport.png
    - lib/assets/images/cloud.png
    - lib/assets/images/child_playing.png
    - lib/assets/images/student.png
    - lib/assets/images/fo_report.png
    - assets/sounds/emergency_tone.mp3
    - lib/assets/images/notification.png
    - lib/assets/
    - assets/mobilefacenet.tflite
    - lib/assets/images/registration.png
    - lib/assets/images/recognition.png
    - lib/assets/images/absent.png
